name: Aiyagari1994QJE
channels:
  - conda-forge
  - econ-ark

dependencies:
  - python=3.11.13
  - pip=24.3.1
  - jupyter=1.1.1
  - notebook=7.2.2
  - matplotlib=3.7.3
  - numpy=1.25.2
  - scipy=1.11.4
  - pandas=2.0.3
  - ipython=8.18.1
  - pip:
    - econ-ark==0.13.0
